#!/bin/bash

echo "Running pre-commit hook: Autoforamt and Compile project"

find src test -name '*.cpp' -or -name '*.hpp' | xargs clang-format -i

# 运行 make
if ! make all; then
    echo "Error: Compilation failed. Commit aborted!"
    exit 1
fi

echo "Compilation successful. Proceeding with commit."
echo ""
exit 0

